name: ci

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: "0 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: fuyi
        run: |
          git config --local user.email "fuyiyuyun@126.com"
          git config --local user.name "fuyi0419"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
